apiVersion: apps/v1
kind: Deployment
metadata:
  name: ole-anders-nginx-deployment
  labels:
    app: ole-anders-nginx
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ole-anders-nginx
  template:
    metadata:
      labels:
        app: ole-anders-nginx
    spec:
      containers:
        - name: ole-anders-nginx
          image: nginx:1.24.0-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "150m"
